import = [
  "~/.local/share/omakub/defaults/alacritty.toml",
  "~/.local/share/omakub/themes/alacritty/tokyo-night.toml"
]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
size = 7
